### ISSUE TITLE
Add comparison with the Schubfach algorithm

### ISSUE THREAD

**Issue by plokhotnyuk** [pjfanning/double-reader-writer#1]
"The Schubfach way to render doubles" by Raffaello Giulietti: 
https://drive.google.com/file/d/1luHhyQF9zKlM8yJ1nebU0OgVYhfC6CBN/view

Sources with the license are here: 
https://github.com/c4f7fcce9cb06515/Schubfach/blob/3c92d3c9b1fead540616c918cdfef432bca53dfa/todec/src/math/

**Comment by pjfanning** [comment]
thanks @plokhotnyuk - one issue is that code depends on Java 9 method java.lang.Math.multiplyHigh - do you know of a java 8 port?

**Comment by plokhotnyuk** [comment]
@pjfanning You can use Karatsuba technique like [here](https://github.com/plokhotnyuk/jsoniter-scala/blob/c70a293ac802dc2eb44165471d76d7df2d4657b6/jsoniter-scala-core/native/src/main/scala/com/github/plokhotnyuk/jsoniter_scala/core/JsonWriter.scala#L1777-L2107)

**Comment by pjfanning** [comment]
added
